// you didn't add this file generated by prisma cli. Please look at package.json
import { User } from "@prisma/client";

import { sign } from "jsonwebtoken";
import { config } from "../config/config";

import { v4 as uuidv4 } from "uuid";
import { addRefreshToken } from "./refreshToken";

export const generateAccessToken = (user: User): string => {
  return sign({ userId: user.id }, config.token_key.access, {
    expiresIn: config.token_expires_in.access,
  });
};

export const generateRefreshToken = (user: User, jti: string): string => {
  return sign(
    {
      userId: user.id,
      jti,
    },
    config.token_key.refresh,
    {
      expiresIn: config.token_expires_in.refresh,
    }
  );
};

export const generateTokens = async (user: User) => {
  const jti = uuidv4();

  const accessToken = generateAccessToken(user);
  const refreshToken = generateRefreshToken(user, jti);

  await addRefreshToken(jti, refreshToken, user.id);

  return {
    accessToken,
    refreshToken,
  };
};
